# Generated by Django 3.1.2 on 2020-12-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0004_auto_20201224_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='AccountsApp.Tag'),
        ),
    ]
